### ISSUE TITLE
Redesigned Landing Page

### ISSUE THREAD

**Issue by AsstroGrill** [codeforboston/communityconnect#131]
![landing page before selection](https://user-images.githubusercontent.com/45612032/49842380-539dd680-fd89-11e8-9114-07f32437ad83.png)

![landing page after selecting saved resource](https://user-images.githubusercontent.com/45612032/49842385-58628a80-fd89-11e8-9d0a-d41772432af4.png)

![resources with map](https://user-images.githubusercontent.com/45612032/49842404-644e4c80-fd89-11e8-91ce-9ac4ac6742f4.png)

**Comment by ndesai06** [comment]
- [x] Saved Resources - "Add to cart" feature
- [ ] Unique URL using ID from Spreadsheet - URL indicates what resources are viewed (including URL for all resources)
- [ ] Move Categories to Left Third - view all + select one or more; scrollbar if needed
- [ ] Move Org Cards to Middle and Right Third - 2 rows; Organized left to right, down a row, left to right, etc.
- [ ] Saved Resources - Link to Unique URL w/ Saved Resources
