### ISSUE TITLE
Privacy Feature

### ISSUE THREAD

**Issue by MattNoName** [codeforboston/communityconnect#134]
There should be a way of handling privacy with the unique link.

Current proposal:  If the user is not in incognito or private browsing mode, detect this and have a red warning symbol that says "Not in Incognito or Private Browsing Mode".

Design wanted!

**Comment by sayansaha1143** [comment]
Can refer this [link](https://www.npmjs.com/package/is-incognito) when we want to add this feature.

**Comment by RingsOfSaturnMR** [comment]
That link seems great, but I think we will need other ways to support other browsers.  I noticed it includes in its dependency "is-chrome".  I think this only works for detecting a private session in chrome.

**Comment by RingsOfSaturnMR** [comment]
Some browsers to try and support:

Chrome, Edge, Firefox, Safari, Opera, Safari for iOS, Android web view, Chrome for android, Edge Mobile, Firefox for android, Opera for android, Samsung Internet, Internet Explorerer

**Comment by RingsOfSaturnMR** [comment]
I proposed a plan before, but it got shot down.  In many browsers you currently can replace an item from the user's history.  Why not just replace this page's url from the client's browser history as soon as it is created?  (With something that's not private, such as google.com)

Here' MDN's documentation on this, in it check out replaceState():

[https://developer.mozilla.org/en-US/docs/Web/API/History_API](https://developer.mozilla.org/en-US/docs/Web/API/History_API)

**Comment by timtheguy** [comment]
This issue has not received much traction since it's proposal - the individual is not tied to the link, and there is no profile generation taking place. Further privacy issues should be explored in a new, concise issue.
