### ISSUE TITLE
Search is busted

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#144]
error in the console

**Comment by bran-van-d** [comment]
I don't know if this issue is the same, but I'll post here first before we confirm. 

When attempting to Search Resources, this error comes up in the console: 

![image](https://user-images.githubusercontent.com/14808841/51576657-20b92900-1e85-11e9-9d32-a797a4f34b8b.png)

**Comment by sayansaha1143** [comment]
This issue should be fixed in the latest PR.
