### ISSUE TITLE
Edit description box of a pin on map

### ISSUE THREAD

**Issue by ndesai06** [codeforboston/communityconnect#15]
Format those boxes to include the information from its row. A designated place for each row (ie. services provided, social media, comments, contact info, etc). Currently the box says "undefined" so maybe that is something to look at too!

**Comment by galiat** [comment]
@ndesai06 & Ashley - Does this pertain to the list on the left or the Marker on the map?

**Comment by ndesai06** [comment]
@galiat This was in reference to the marker on the map itself!

**Comment by galiat** [comment]
ok - lets chat about this tonight. Its easy to do from a code point-of-view, but I think we should be careful with how much information we put in those markers. (could get large) 

One idea we had talked about last week was that when a user clicks a Marker, we scroll to the entry in the list on the left.
