### ISSUE TITLE
Move left side panel to the border of Header

### ISSUE THREAD

**Issue by ndesai06** [codeforboston/communityconnect#166]
Currently, the left side panel, both the category list and the card list in the map page, are pushed down to accommodate for the logo. Now with the logo removed, the left side panel should go back in line with the ride side panel.

**Comment by SimonPringleWallace** [comment]
I'm still seeing a logo on the master branch (blue house with 'community connect' underneath). Is this issue blocked by #165, or is there a different branch that has no logo that I should work off of (...or have I completely misunderstood the ticket)? Thanks!
