### ISSUE TITLE
Adding Scroll bar on Category List

### ISSUE THREAD

**Issue by ndesai06** [codeforboston/communityconnect#170]
Currently, the Category list on mobile is hiding 4 categories after "Healthy Foods and Food Pantries".

**Comment by galiat** [comment]
Context: some categories don't showup in mobile because they get cut off

**Comment by bfeif** [comment]
https://github.com/codeforboston/communityconnect/blob/master/src/components/SlidingPane/SplitScreen.module.css

If I just set `overflow: scroll` in `.slidingPane` in the above css file, then the category list becomes scrollable. However, then the button to open/close the category drop-up becomes irrevocably hidden. Any ideas? I've tried styling the button, but can't figure it out.

Before:
<img width="489" alt="screen shot 2019-02-07 at 4 41 16 pm" src="https://user-images.githubusercontent.com/12984962/52444751-4423db00-2af7-11e9-9b30-ad63d8803bf9.png">

After:
<img width="494" alt="screen shot 2019-02-07 at 4 40 50 pm" src="https://user-images.githubusercontent.com/12984962/52444766-500f9d00-2af7-11e9-882c-813f1b60bb2b.png">

**Comment by sayansaha1143** [comment]
This scroll change should be good for now. Our final idea is to move the category list completely to the three line filter button on the top right for the mobile view (which I assume would still be scrollable after this change). So I don't think we need to worry about the button here.

**Comment by bfeif** [comment]
But, without the button, the drop down list cannot be re-hidden, obfuscating the rest of the screen's contents.

**Comment by galiat** [comment]
![filter overlay](https://user-images.githubusercontent.com/757518/52527484-25f4e100-2c97-11e9-8850-50f356c217f0.png)

@bfeif - these are the new designs from Will. We still need those css change.

**Comment by bfeif** [comment]
> This scroll change should be good for now. Our final idea is to move the category list completely to the three line filter button on the top right for the mobile view (which I assume would still be scrollable after this change). So I don't think we need to worry about the button here.

@sayansaha1143 So, should I push these changes then? Or wait until the new designs for this "Category" view are implemented.

**Comment by sayansaha1143** [comment]
You can push now, after you merge your changes with the latest.
