### ISSUE TITLE
on Saved Resources, the 'to map' link needs to stand out more

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#185]
use color & style

**Comment by AsstroGrill** [comment]
<img width="640" alt="savedresourcesredes" src="https://user-images.githubusercontent.com/45612032/53438805-aec98780-39ce-11e9-93f9-c3f8ad420c24.PNG">

Something like this, perhaps? Looks the same as the "Saved Resources" button, but it's in the pop-up 

There's also what seems like unnecessary space at the bottom of that pop-up box. We could either get rid of the space or put "To Map" there, though that might be more out of the way for the users.

**Comment by timtheguy** [comment]
Looks like this issue should focus on the alignment of the two menu items - the main content (with title and 'Saved Resources' button) followed by the secondary actions, Search and Sort. Whoever addresses this PR, feel free to recolor the navigation area (above) and address this bug by breaking the components into new rows.

**Comment by ValerieKenyon** [comment]
I just did a little bit with styling the pop-up box.  I don't quite understand everything in the above comments, so I didn't do everything that's been brought up here.  The branch with my changes is VK_issue_185.

**Comment by timtheguy** [comment]
This issue could use some design perspective, but is otherwise open to work. @galiat, do you have this assigned to you for any reason?

**Comment by ndesai06** [comment]
Closed because new UI from Juan
