### ISSUE TITLE
Add & use new Category Filter icon in Mobile View

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#186]
get file from slack here: https://cfb-public.slack.com/archives/CC85SAJ0Z/p1549501248024600

looks something like 👇 , but use the file in slack ☝️ 
![image](https://user-images.githubusercontent.com/757518/52527587-2c845800-2c99-11e9-9730-bdd44d59cec3.png)

**Comment by timtheguy** [comment]
I wasn't able to track down where we are using this filter graphic in mobile or desktop viewports. Closing the issue unless it needs to be reopened!
