### ISSUE TITLE
Change - icon back to + when resource is removed from list (continuation of #167) 

### ISSUE THREAD

**Issue by acharliekelly** [codeforboston/communityconnect#201]
Button now turns to - when you add a resource (per issue #167). But it needs to turn back when you remove the resource. Also, clicking it again will always turn it back to a plus, but that doesn't mean the resource is removed from storage. This is because it's just a toggle switch, rather than being bound to the state of the resource.

**Comment by sayansaha1143** [comment]
According to what I discussed with @galiat , you could completely remove the part where clicking on the "check-mark" turns it back to a "+" button. Instead now, only way to remove saved resources would be from the saved resource panel (by clicking on the "-" button). Also this would mean, clicking on "check-mark" button would not remove the resource id from url.

@ndesai06 @Khoawala you guys can weigh in on this PR and give your thoughts.

**Comment by hjpatel16** [comment]
Hello, can I work on it?
