### ISSUE TITLE
Add Count to Saved Resources 

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#204]
So if there is more than 1 resource selected the button should read `Saved Resource (1)`

**Comment by jatinkumarg** [comment]
Hey, can I work on this issue?

**Comment by galiat** [comment]
@jatinkumarg As a general rule, if an issue is already assigned to someone then they are working on it. In this case the issue was already resolved by @vipinchacko & I forgot to update its status (will do that now).

I do appreciate your enthusiasm tho! If you want to be involved with the Code for Boston team join our [slack](https://communityinviter.com/apps/cfb-public/code-for-boston) and find the Community-Connect channel. We use to discuss project direction, requirements etc.

We do try to save the [Good First Issue] tasks for those who either have never contributed to open source or those who want to actively be a part of the team, so minimally please join our channel & introduce yourself before taking on an issue.

I'm glad you asked tho - it made me realize the project was missing a contributing.md

**Comment by galiat** [comment]
resolved!
