### ISSUE TITLE
Update 'Category' text

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#206]
Update the wording from `Category`  to `Filter by Category`

![image](https://user-images.githubusercontent.com/757518/53061658-43426000-348c-11e9-8b01-75d833cf5777.png)

**Comment by galiat** [comment]
I'm not resolving this - just holding it for an interested person

**Comment by jatinkumarg** [comment]
Hey, can I work on this?

**Comment by jatinkumarg** [comment]
Since it was a easy fix, I have already submitted a [PR](https://github.com/codeforboston/communityconnect/pull/216).

 Please review it and let me know if any further changes are required.
