### ISSUE TITLE
Update Org Card so social media links are text

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#207]
![image](https://user-images.githubusercontent.com/757518/53061778-b77d0380-348c-11e9-8f31-a82e56fc62d0.png)

the social media links are ugly. Update it so that its just the work 'Facebook' or 'Twitter.' 

At some point we may change this to be icons, but for now keep it simple & just use the words

**Comment by rahulmotan** [comment]
I'll be working on this.

**Comment by galiat** [comment]
Ya sure- the only reason I was avoiding was because I'm not sure visually exactly how we'd want them. But if you are up for it & okay that they may be tweaked after March 1, then feel free

**Comment by rahulmotan** [comment]
so far I've done this, let me know if this suffices for March 1 release.

![image](https://user-images.githubusercontent.com/20379052/53121413-2eb0a700-3522-11e9-97c7-80a7044e1e38.png)

**Comment by rahulmotan** [comment]
This is just my opinion, we could simply make the title of the card a link. Although I'm sure much discussion would have gone into the current layout. The reason is, the text below the title starts where the link icon is placed, which kinda looks weird to me. Any suggestions to make improvements to that? I'm up for it.

**Comment by sayansaha1143** [comment]
> This is just my opinion, we could simply make the title of the card a link. Although I'm sure much discussion would have gone into the current layout. The reason is, the text below the title starts where the link icon is placed, which kinda looks weird to me. Any suggestions to make improvements to that? I'm up for it.

That is actually a good idea. We never really gave a lot of thought about the aesthetics of each card until just now, since most of us were trying to get all the functionalities completed. But I would suggest if you are up for it and have something in mind you can try to play around with it and drop a sample of how you think it could look on our slack channel and we can all discuss on it, and then when we settle on something you can put in another PR for the same.

**Comment by rahulmotan** [comment]
Great, Thanks. I'll try to see if I can come up with some responsive designs until the next hack night.

**Comment by galiat** [comment]
>This is just my opinion, we could simply make the title of the card a link.

The person I did user testing said the exact same thing! The original reasoning was that on map view, clicking the title within the OrgCard would bring you to the pin on the map. I have a note to revisit this after March1 since we care less about the map now

& I agree with @sayansaha1143 100% We need to think about OrgCard more, however it might be better to do that *after* March 1 because @ndesai06 plans on doing user testing to determine what information is the most relevant to social workers & that would inform any design changes.

Which isn't so say I'm opposed to pre-March1 changes, just saying we can make better informed changes after user testing

**Comment by galiat** [comment]
oh & to answer your original question - the social media links look great!

**Comment by ndesai06** [comment]
I completely agree with @galiat and @sayansaha1143. I think we should wait to see how the product is actually used by the SWs before we implement functionality changes. But I would assume that they're going to agree with what you propose @rahulmotan. Great work!

**Comment by rahulmotan** [comment]
Thank you, guys. I'll do the changes as per what I think would be best. If they seem a little over the top then I'd level it down a bit. But I won't change the entire design rather fix alignment of things.

**Comment by AsstroGrill** [comment]
The social media links look great! I think for usability, we may want to add the name of the social media site (Facebook, Twitter, etc.) next to the icon as well. Knowing how small the cards can be, it might be a bit difficult if someone is trying to click it, especially with some of the resources/categories we are providing, such as Elderly Support. Just an idea!
