### ISSUE TITLE
When a Category is selected for filtering, display it

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#21]
Would love for people with an eye for design to chime in. When a category is selected & we are filtering results, it would be handy for our user to know that a filter is in place & what that filter is. 

How it currently looks is displayed below. Was thinking:
* in the dropdown:  have a checkmark or have the selected one be another color.
* in the header next to 'Categories' display the currently selected category. 

![image](https://user-images.githubusercontent.com/757518/45057268-2e4f4d00-b063-11e8-84bd-edd82c08ab61.png)

**Comment by sophiaminmorgan** [comment]
Are all resources correlated with only one category, or can they be a part of multiple categories?

**Comment by galiat** [comment]
they can be a part of more than 1 categories

**Comment by Khoawala** [comment]
I've added an "all" item to the top of the list to retrieve the entire category list. And as for some kind of selected marker.... I've just changed the category header to the selected category. Shown below... What do you think?
![image](https://user-images.githubusercontent.com/14927557/45195661-b0d43a00-b226-11e8-8d8d-e56076939028.png)

**Comment by galiat** [comment]
I like it! I think its a solid improvement for now & we can tweak the UI as designers have time.
