### ISSUE TITLE
Allow social worker to input address relevant to the client

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#211]
A likely scenario is that the social worker will want to find resources close to the clients home/work.

Unfortunately right now the distance sort is based on the social worker current location. How can we allow the social worker to enter an address that might more relevant to the client?

I was thinking perhaps when they select sort by distance have a prompt to let them change the 'location'

**Comment by AsstroGrill** [comment]
Google has an option to input location when you click directions, shown below. Would you like to implement something like this?

![googledistancedesign](https://user-images.githubusercontent.com/45612032/53437304-285f7680-39cb-11e9-806f-8cf7562ca4b6.PNG)

**Comment by AsstroGrill** [comment]
I notice that, if on our site, you click "get directions," it just brings me to Google Maps. If its too big a feature to implement, or something that we would work on after launch, we could tell the users in the meantime to use the link(s) available to them, as they are available

**Comment by timtheguy** [comment]
We are basing the need for this issue based purely on speculation. I think that we might want to consider closing this issue until we get feedback from a social worker that this is something useful for them
