### ISSUE TITLE
[beginner friendly] display resource phone number in list on the left

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#22]
For example, the hotlines are not displaying a phone number right now.

**Comment by ndesai06** [comment]
It is now showing the phone number, however. there is a spacing issue with a random comma appearing in the middle of the box.

**Comment by irvang** [comment]
The phone issue is resolved. 

I believe the address issues would be resolved on App.js, line 24, where element.location is defined. I believe it is a matter of just putting an if statement so that a blank comma is not left there if there if none of the address elements are present.

**Comment by irvang** [comment]
Ok, I created a pull request addressing what I mentioned. I should now not display the comma when the Hotline category is selected.

**Comment by irvang** [comment]
Issue is solved.
