### ISSUE TITLE
Resource cards are not the same height 

### ISSUE THREAD

**Issue by timtheguy** [codeforboston/communityconnect#220]
The resource cards in both the admin and client view should maintain the same height from row to row. Currently, the cards appear as below when resources do not fill the cards:
![image](https://user-images.githubusercontent.com/9803215/53457413-57dca600-3a00-11e9-8e33-a4888b3091fa.png)

This issue should give way to a PR that makes all cards the same height per row, possibly with a minimum height attribute (`min-height: ###px`)

**Comment by alxhghs** [comment]
I played with this and think I have a good fix. Let me know if I should create a PR 
<img width="819" alt="image" src="https://user-images.githubusercontent.com/13875792/53565431-7b4e4080-3b27-11e9-979a-fbbfd686aac5.png">

**Comment by timtheguy** [comment]
Hey Alex, I had originally claimed the issue but it looks like you're well ahead in getting it fixed - go ahead and create the PR for review!

**Comment by alxhghs** [comment]
Thanks Tim, I didn’t want to step on your toes but I was playing around with it this morning just out of curiosity and thought it looked pretty good.

**Comment by alxhghs** [comment]
Added a PR for this here: https://github.com/codeforboston/communityconnect/pull/231

**Comment by rahulmotan** [comment]
The cards do look nice with a consistent height and my changes 😄

**Comment by alxhghs** [comment]
:-)
