### ISSUE TITLE
Improve Layout to Two Card Columns for all screens

### ISSUE THREAD

**Issue by timtheguy** [codeforboston/communityconnect#224]
In the landscape iPad viewport, the three columns of cards should drop down to two columns of cards, such that content is displayed as intended. Currently, the layout appears as below:

![image](https://user-images.githubusercontent.com/9803215/53458104-c9b5ef00-3a02-11e9-9e99-c8bba1c60d6c.png)

It should appear as above, but with only two columns and the categories to the left. 

_Note: Future implementations of the mobile and tablet layout will collapse the categories list. This issue exists to resolve the viewport issue in tablet view._

**Comment by alxhghs** [comment]
merged
