### ISSUE TITLE
Search form field moves with search result column count

### ISSUE THREAD

**Issue by timtheguy** [codeforboston/communityconnect#225]
Currently, in the desktop viewport, searching with less than 3 results in the row moves the search bar with the search results. With three or more results, it appears as below:

![image](https://user-images.githubusercontent.com/9803215/53458263-67112300-3a03-11e9-80ea-5e955c2f274a.png)

With two results, it moves to the right some more:

![image](https://user-images.githubusercontent.com/9803215/53458272-709a8b00-3a03-11e9-8c31-55a2c3f253c9.png)

With one result (or none) the search result moves to the center along with the search field:
![image](https://user-images.githubusercontent.com/9803215/53458293-83ad5b00-3a03-11e9-8b0a-6dafbed72d90.png)

**Comment by rahulmotan** [comment]
I'm gonna try and fix this. I'll assign this to myself once I figure out a solution.

**Comment by rahulmotan** [comment]
Fixed this but my changes causes the scroll bar to appear on "/" page. Attaching screenshots.
![image](https://user-images.githubusercontent.com/20379052/53544581-90f64280-3af4-11e9-839c-02ba52fe1e4b.png)
![image](https://user-images.githubusercontent.com/20379052/53544631-bbe09680-3af4-11e9-9585-0448d3f31845.png)

**Comment by rahulmotan** [comment]
Let me know if you want me to create a pull request.

**Comment by alxhghs** [comment]
Added some comments to your PR. I think it would be ideal if the changes were isolated to the admin page and didn't impact "/". Could we create an additional class to differentiate between the map and the admin page so that the changes don't impact both pages?

**Comment by alxhghs** [comment]
Also, nice work, the admin page looks a lot better with this change

**Comment by rahulmotan** [comment]
> Added some comments to your branch. I think it would be ideal if the changes were isolated to the admin page and didn't impact "/". Could we create an additional class to differentiate between the map and the admin page so that the changes don't impact both pages?

I did try that. The entire app is wrapped with that div and it has a CSS property of "overflow": "hidden" to hide the scroll bar on page "/". I did try fixing it with many alternate approaches but so far unsuccessful.

**Comment by alxhghs** [comment]
Maybe this is something we can look at again later then.
