### ISSUE TITLE
Update name on browser tab

### ISSUE THREAD

**Issue by ndesai06** [codeforboston/communityconnect#230]
Currently, the name on the browser tab says "Find Revere Resources l powered by Makao". It would be great if this could be changed to "Community Connect" for continuity purposes. Also, the resources that are currently listed in the database are not confined to Revere and go into the Greater Boston Area.

<img width="1054" alt="screen shot 2019-02-28 at 8 24 36 am" src="https://user-images.githubusercontent.com/42190870/53569477-514e4b80-3b32-11e9-99f9-1f187b62d654.png">

**Comment by alxhghs** [comment]
I noticed this comment in the issue as well, but I’m not sure how to address it. " Also, the resources that are currently listed in the database are not confined to Revere and go into the Greater Boston Area."
