### ISSUE TITLE
Npm or yarn

### ISSUE THREAD

**Issue by Khoawala** [codeforboston/communityconnect#233]
While resolving the security issue by doing the yarn install to update the yarn-lock package. It showed me a warning.
![image](https://user-images.githubusercontent.com/14927557/53586703-ba47ba80-3b56-11e9-81ec-f9e08b13cae7.png)

This makes sense. The yarn-lock file is never updated because we mostly use npm so we should decide to only use one of these tools.

**Comment by alxhghs** [comment]
I like yarn, but both are good

**Comment by rahulmotan** [comment]
Yeah it's wiser to have only one package manager

**Comment by Khoawala** [comment]
Would github still show the vulnerability even if it's on .gitignore? How about we just delete the yarn.lock for now?

**Comment by alxhghs** [comment]
Pretty sure gitignore wouldn't matter since it's still a dependency of a package in package.json

**Comment by alxhghs** [comment]
Did we decide on yarn or npm? We say yarn in the README, so maybe we should add `package-lock.json` to `.gitignore`

**Comment by alxhghs** [comment]
Created a PR #246 if this is what we want to do

**Comment by Khoawala** [comment]
@alxhghs  Hey I think we should use npm as most members are using npm at the moment. Plus, yarn.lock is currently the outdated package that is giving security issues. Can you remove yarn.lock in your pull request?

**Comment by alxhghs** [comment]
PR #249 removed yarn and switched us to NPM. Closing this issue
