### ISSUE TITLE
Saved resources button conflicting with sort distance

### ISSUE THREAD

**Issue by sayansaha1143** [codeforboston/communityconnect#237]
![image](https://user-images.githubusercontent.com/23369510/53595560-9a6ec180-3b6b-11e9-97ee-c4598ee83a59.png)

Not sure what changed but, in the current version as we add a resource the count on the save resource button goes to the next line and creates a conflict with the sort by box

**Comment by alxhghs** [comment]
I built out a fix for that. I can make a PR

**Comment by alxhghs** [comment]
Things are really slow for me at work today :)
