### ISSUE TITLE
Cards scrolling laterally on list view of normal user

### ISSUE THREAD

**Issue by ndesai06** [codeforboston/communityconnect#240]
Currently, the org cards on the left side of the screen are slightly bigger than the allocated margin of the left panel, which is allowing there to be a small scroll from left to right.

<img width="406" alt="screen shot 2019-03-03 at 3 49 41 pm" src="https://user-images.githubusercontent.com/42190870/53701526-17987180-3dcc-11e9-9d02-f2915c258983.png">

<img width="388" alt="screen shot 2019-03-03 at 3 49 50 pm" src="https://user-images.githubusercontent.com/42190870/53701527-1bc48f00-3dcc-11e9-941a-c39ca05b731a.png">

**Comment by alxhghs** [comment]
I think if we redo the layout using CSS Grid instead of Bootstrap it will be easier to keep things like this from happening.
