### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by alxhghs** [codeforboston/communityconnect#241]
I noticed that some files use 4 spaces and some use 2 spaces. We also use " in some cases and ' in others. What do you all think about using ESLint so that we have some consistency in how we format the code? I also found this, which I haven't tried yet, but it looks pretty nice.

https://www.npmjs.com/package/standard

The nice thing about using a linter is that it makes the code cleaner and easier to read.

**Comment by alxhghs** [comment]
Here are some of the companies that use `standard`: 

https://www.npmjs.com/package/standard

**Comment by Khoawala** [comment]
#247
