### ISSUE TITLE
Develop branch?

### ISSUE THREAD

**Issue by alxhghs** [codeforboston/communityconnect#242]
What do you all think about creating a separate develop branch instead of pushing everything to master? Sometimes that's a good practice so that the master branch stays clean and if we break anything as we are developing then it's only in the develop branch and not master. Then when we are ready to have a bigger update, we push everything to master. Wouldn't be too hard to implement and might be good going forward as this project starts to get used for real.

**Comment by alxhghs** [comment]
Any any urgent fixes could go straight to master if needed and then merged into develop.

**Comment by timtheguy** [comment]
Hey @alxhghs - I think this is a good idea. It would help to 'triage' new changes being made and allow them to be reviewed by stakeholders before moving into a main release.

**Comment by Khoawala** [comment]
New branch created called "development" which is now set as the base branch for this repo. I think that's how this works....

**Comment by timtheguy** [comment]
@Khoawala - sort of. We will now need to make sure that folks are making all pull requests to the `develop` branch instead of `master` - this includes outstanding PRs. Perhaps we should create a roadmap / implementation plan along with an update to the contribution guide before using a new `develop` branch.

**Comment by timtheguy** [comment]
Here's a closer look at how we might implement the `develop` branch: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by alxhghs** [comment]
We have a development branch now! Closing this issue
