### ISSUE TITLE
Org card social media link different in Saved Resources

### ISSUE THREAD

**Issue by ndesai06** [codeforboston/communityconnect#244]
Currently, the social media links at the bottom of the org card in list view of admin is accessible through the respective social media icons. However, when the org card is added to the saved resources to create a unique url, the social media icon is removed and the social media link is directly written out (in large font).

<img width="823" alt="screen shot 2019-03-07 at 8 50 56 am" src="https://user-images.githubusercontent.com/42190870/53961386-7274e600-40b6-11e9-8e15-12fe88927148.png">

**Comment by Khoawala** [comment]
For anyone working on this, we should use the icon from the package FontAwesomeIcon that is currently being used for all social media icon in the OrganizationCard.js
