### ISSUE TITLE
Flow?

### ISSUE THREAD

**Issue by alxhghs** [codeforboston/communityconnect#245]
Anybody have any experience using Flow? I think it could be a good addition to this project both for documentation and for type safety. I'm playing around with Flow in a branch and I've noticed a couple bugs that I wouldn't have noticed without it. It would also help with documenting how things work for new people.

[https://flow.org/en/](https://flow.org/en/)

**Comment by timtheguy** [comment]
Hey @alxhghs - I appreciate the initiative to add new functionality to our development platform - however, I don't know that this is issue is very actionable for contributors as it is merely posed for discussion. I am going to close it for now until it can be re-opened as something we can implement from a development perspective!
