### ISSUE TITLE
Add Search and Filter Feature to Client View on Desktop and Mobile

### ISSUE THREAD

**Issue by ndesai06** [codeforboston/communityconnect#252]
Right now, only the admin view `/revere/admin` displays a search and filter option, displayed below:
![image](https://user-images.githubusercontent.com/9803215/58141012-bf754c80-7c0f-11e9-9f82-c7936392e95c.png)

Social workers have expressed interest in including this functionality in the traditional client view, for those that are accessing a larger number of resources or simply browsing resources in their area.

This issue is addressed when the search and filter functionality is built back into the client view.

**Comment by ndesai06** [comment]
Update: Search and Filter feature on regular user view

**Comment by timtheguy** [comment]
I've updated the issue details - design proposals and pull requests welcome!

**Comment by ndesai06** [comment]
Client View: https://communityconnect.netlify.com

**Comment by AsstroGrill** [comment]
Do you want a mockup for this? I can work on it :)
