### ISSUE TITLE
Admin - Toggle between Map and Resource Card (List) View

### ISSUE THREAD

**Issue by ndesai06** [codeforboston/communityconnect#265]
Currently, resource cards are only shown as a list view on the admin page. However, after implementing a "sort by radius" feature, it would be more effective to have the option to see the resources as pins on the map.

**Comment by timtheguy** [comment]
Hey @ndesai06 - are you suggesting that we add a map to the `/admin` view, so that the resources can be browsed by location on the map or by list?

**Comment by ndesai06** [comment]
Hey @timtheguy  - I think it would be useful for administrators to be able to view resources on a map before "prescribing" health resources to their clients. This way they don't have to click "get directions" every time to view a resource on a map.
