### ISSUE TITLE
Design task - Print Saved Resources 

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#269]
@Morenosanabria (Juan) mentioned that a feature that could print the ’shopping cart’ would be vital at his old clinic for 2 different reasons.

1. Clients often had low-end androids (those Obama phones) or where not at all tech savvy, so for them a print out would be better 
2. For record keeping. They would get audited (apparently this is common) and that audit process has auditor looking at their client’s charts & seeing what services they had recommended. Charts are still all on paper, so they need an easy to - via paper- document recommended services in the client’s chart.

He also said that print option might make it easy for older directors to buy into it, but that might be because of 1 or 2 vs as a 3rd reason. 

Some questions: 
1) Where should the print button be?
2) what should the print out look like?

**Comment by debanjana** [comment]
Hi ! 
I am working on this. 
The mockup is available at the following link:
https://xd.adobe.com/view/bae961a4-7d01-4680-4de1-2f77471ebcaa-ccd8/?fullscreen

Please select Mobile to see Mobile Layout Mocks and Web to see Web Layout. 

The Print Button for this issue is available in the Saved Resources Page in Web Layout. 
Click on the "Shopping Cart" button to view Saved Resources and view the Print option.

**Comment by timtheguy** [comment]
After discussing further internally, we've decided to add a print button to the client view - based on what you shared in your mockups. Here's a simple look at what that would be: 
![Screen Shot 2019-06-11 at 8 14 30 PM](https://user-images.githubusercontent.com/9803215/59315081-2c678980-8c86-11e9-9950-6b11c834df38.png)

We have a location for the print button, and [a mockup of a printed page](https://slack-files.com/T0556DP9Y-FJY1GRLUS-cf3a58df46) has been created! 🎉 Closing this issue to make way for development on version 1.0 - a new issue should be created for the next step of design consideration for this print layout.
