### ISSUE TITLE
Distance from current location

### ISSUE THREAD

**Issue by sayansaha1143** [codeforboston/communityconnect#27]
I think it would be helpful for users if along with the address of the location, we could add a distance in miles from the current user's location for each of our displayed result.

**Comment by microcat49** [comment]
In my last pull request I created a function called `getDistance()` . It will return the distance between two geographical points. I might move the function to its own file so it can reference through out the application. 

I can pass the current location through `ResultList ` to each individual ` OrganizationCard ` and have the distance calculated in each card?
