### ISSUE TITLE
load category groupings

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#271]
Use Column D in the spreadsheet for now. 
Note that a Resource can have more than one Category Grouping that applies to it.

If you are new to the codebase, I'd recommend looking to see how categories are populated when we initially get the data from the google sheets api.

**Comment by acharliekelly** [comment]
I submitted a PR for this, which (I think) exposes category groups (column D in the spreadsheet) as another resource, just like categories. So now somebody can use that to do something on the front-end, so categories are broken up into groups.

**Comment by acharliekelly** [comment]
This issue was subsumed by #285, which was then merged with #291. Fixed in #295.
