### ISSUE TITLE
Change Title in Database and Reflect in Code [Service Provided -> Mission]

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#281]
When reading data from the sheet, right now we grab something called 'overview.' Update the code so that we first look for something called 'mission' and if its not there, then look for something called 'overview'

**Comment by ndesai06** [comment]
UPDATE:
Current title: Service Provided
and hopefully it will be changed to...
New Title: Mission

**Comment by ndesai06** [comment]
Closed due to relevancy
