### ISSUE TITLE
On listview handle long org overviews/missions

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#283]
on the list view, truncate 'overview' (or may be called 'mission') to 500* characters and then if user clicks it, expand to show the whole thing

Note: 500 is arbitrary. If you think another value works better, use that.
![image](https://user-images.githubusercontent.com/757518/58130041-1ddb0480-7be9-11e9-9e34-f115f64d733b.png)

**Comment by RajChaudhry** [comment]
See #304
