### ISSUE TITLE
Remove Sort Option from the Saved Resources Page

### ISSUE THREAD

**Issue by debanjana** [codeforboston/communityconnect#288]
We could remove Sort Option from the Saved Resources Page as it probably is not being used.
<img width="1046" alt="Screen Shot 2019-05-21 at 8 56 50 PM" src="https://user-images.githubusercontent.com/7845597/58140046-7ae7b200-7c0b-11e9-9a19-b98b2c7bbe3a.png">

**Comment by timtheguy** [comment]
Hi @debanjana - what do you mean that it is not being used? It seems like it works correctly and provides helpful functionality to users

**Comment by ndesai06** [comment]
@debanjana I agree with @timtheguy. But let's talk about this and other UX/UI issues on Tuesday!
