### ISSUE TITLE
Change Title in Database and Reflect in Code [(TESTING) Category Groups -> Head Category]

### ISSUE THREAD

**Issue by ndesai06** [codeforboston/communityconnect#291]
Current title: (TESTING) Category Groups
and hopefully it will be changed to...
New Title: Head Category

**Comment by timtheguy** [comment]
Hi @acharliekelly - was this issue fixed? I see you closed your pull request (#285) without merging.

**Comment by acharliekelly** [comment]
My previous PR for issue #285 was directly related to issue #291, so I closed it and changed it to address both issues. Now instead of adding Category Groups, it adds Head Categories (because that's what we're calling the info in Column D now)
