### ISSUE TITLE
Change Title in Database and Reflect in Code [(TESTING) Sub-Category -> Sub Category]

### ISSUE THREAD

**Issue by ndesai06** [codeforboston/communityconnect#292]
Current title: (TESTING) Sub-Category
and hopefully it will be changed to...
New Title: Sub Category

**Comment by timtheguy** [comment]
Where do these title changes need to made?

**Comment by RajChaudhry** [comment]
See: /src/api/googlesheetApi.js

**Comment by timtheguy** [comment]
Hi @RajChaudhry - I'm looking at the source for the file you've mentioned, [`/src/api/googlesheetApi.js`](https://github.com/codeforboston/communityconnect/blob/development/src/api/googlesheetApi.js), but I don't see any reference to the old and new titles, such as "_(TESTING) Sub-Category_" - is there something else involved here?

**Comment by RajChaudhry** [comment]
Shoot i was wrong, i was looking at the wrong file, check out /src/components/AdminPage/CategoryList.js . I believe if you just refactor some of the things in the handleChange() method, it should work out. My bad

**Comment by galiat** [comment]
& maintain backwards compatibility of the old title
