### ISSUE TITLE
User-friendly 404 message

### ISSUE THREAD

**Issue by acharliekelly** [codeforboston/communityconnect#306]
If you enter a bad URL (eg "https://communityconnect.netlify.com/badurl"), you get a JS alert that says "Error: Unable to find resource 'badurl'" and a perpetual progress circle. From a UX perspective, this is sub-optimal.

Instead, there should be a more user-friendly "not found" message, and a suggestion for how to correct the problem.

**Comment by galiat** [comment]
David will be taking this one

**Comment by RajChaudhry** [comment]
fixed by @davidholyko in #311
