### ISSUE TITLE
Handle change of "Category (Autosort Script)" column in code

### ISSUE THREAD

**Issue by acharliekelly** [codeforboston/communityconnect#309]
Spreadsheet column F, currently called "Category (Autosort Script)", should be changed in the code to "Category". But it should be backwards-compatible, so that the current name also works - otherwise the app will break as soon as the change is merged.

**Comment by acharliekelly** [comment]
It turns out we can provide an alias in googlesheetApi.js, and then not have to deal with the &$#* column name again. Even if somebody decides to rename the column yet again.

**Comment by RajChaudhry** [comment]
fixed via #332
