### ISSUE TITLE
Sorting selection box aesthetics

### ISSUE THREAD

**Issue by 2001zhaozhao** [codeforboston/communityconnect#313]
The current selection box -
https://i.imgur.com/lXEJ3PC.png
is vague in that by default the sorting is already done alphabetically, but the box shows "select a sort" by default. It should show "alphabetically" by default.

Additionally, I think that a text "sort by" followed by the selection box would be more intuitive than just displaying the selection box itself. I will work on this feature.

**Comment by ndesai06** [comment]
Agreed! Excited to see what you're able to put together

**Comment by RajChaudhry** [comment]
Closed via #320
