### ISSUE TITLE
"Submit feedback" bar blocks the zoom out button on Google Maps

### ISSUE THREAD

**Issue by 2001zhaozhao** [codeforboston/communityconnect#314]
See image:
![Screenshot from 2019-06-11 21-21-29](https://user-images.githubusercontent.com/15002454/59317507-33e06000-8c91-11e9-97cb-afff383cd508.png)

Currently you have to close the bar every time when visiting the app to use the zoom out button in Google Maps. The bar should displace the map & organization list upwards instead of displaying over them.

**Comment by RajChaudhry** [comment]
fixed via #336
