### ISSUE TITLE
Add option to enter manual location for map rather than using your current location

### ISSUE THREAD

**Issue by RajChaudhry** [codeforboston/communityconnect#327]
Currently, our app only utilizes the location of the user when fetching nearby resources in the /:resource page. Some SW's indicated that they would like to search for resources close to their client's house. A good first step then would be to add functionality to add in specific addresses into the map on the client view (/:resource) and from there we can work further on it by adding radius filters.

**Comment by ndesai06** [comment]
Closed #211

**Comment by galiat** [comment]
Closing because this is a duplicate of #400
