### ISSUE TITLE
Add a toggle map/list feature for the /:resource/admin page to easily show where saved resources are located on the map

### ISSUE THREAD

**Issue by RajChaudhry** [codeforboston/communityconnect#328]
We want to be able to make it easy for our SW's to view what resources are being put onto their list in real time. Currently, if they want to see where all their saved resources are in a map, they have to click on the saved resources button, and then the checkout button to see their locations in relation to each other. To make more changes, they would have to go back to their previous tab, make the changes, and checkout again. Making a toggle between a list of resources and a Map would help solve this issue. Refer to this mockup if my explanation sucks: https://marvelapp.com/c054d54/screen/57793613

**Comment by lucaspchartier** [comment]
I'm conflicted on possibly adding a Toggle component under Admin or App. Any thoughts/opinions that anybody wants to share?

**Comment by RajChaudhry** [comment]
Sorry, I don't understand what you mean here. Can you be more specific in what you're asking?

**Comment by ndesai06** [comment]
@lucaspchartier Hey Lucas! Just wanted to check-in on your progress for this feature. Do you need help from anyone else on the CC team?

**Comment by acharliekelly** [comment]
This runs into the same problem as #349: the view _should_ be a state value, and changing the view _should_ be an action. But instead the view, like the resources, is stored in the URL. So putting it in the state as well would be redundant. Therefore, we have a reducer that handles searching and filtering, but resources and view changes are handled by a completely different mechanism, directly in the components. This seems like a bad pattern, but feel like more discussion is needed before unilaterally changing it.
