### ISSUE TITLE
Clicking on the checkmark after saving a resource does not remove it from the saved resource list

### ISSUE THREAD

**Issue by RajChaudhry** [codeforboston/communityconnect#329]
Some SW's who tested our build remarked that they could only remove a resource by going to the saved resource drop down menu and removing it from there. This makes more intuitive sense, and can be a great QoL enhancement

**Comment by acharliekelly** [comment]
Fixed by PR #347. However, code for removing saved resource is just copied from SavedResource to OrganizationCard; should be refactored to avoid redundancy. Will create new issue for refactoring.
