### ISSUE TITLE
Category Collapsible Menu

### ISSUE THREAD

**Issue by RajChaudhry** [codeforboston/communityconnect#340]
In the /admin page, the number of categories available can be overwhelming, and take up a bunch of space. Especially in /revere/admin, we have a lot of categories available to the SW. By making the categories bar on the left one collapsible menu, it can save a lot of space on the screen. Also, it would be a good first step towards fully implementing sub categories, which would act as nested collapsibles.

**Comment by andy7i** [comment]
Code for this is blocked by css refactor, but is implemented here: https://github.com/codeforboston/communityconnect/tree/duyen-andrew-category-collapse
