### ISSUE TITLE
Add eslint to improve code consistency

### ISSUE THREAD

**Issue by johnpyp** [codeforboston/communityconnect#378]
We should add eslint to allow much easier debugging in editors as well as consistent formatting and code style throughout the codebase.

The Airbnb eslint config is a popular and good option for react, but is notably strict and may introduce some friction for newcomers.

The Standard + Prettier configs are also pretty good, but aren't as strict, so they might be more beginner friendly.

**Comment by johnpyp** [comment]
I saw another PR regarding eslint, but it doesn't seem like it's being used (lacking a config).

**Comment by davidholyko** [comment]
i had it in a previous. PR. it seems to have gotten lost with all the merging that happened. 

Feel free to take over this issue.

I did try out the airbnb linter and there were maybe 20+ linting errors in every file. It would definitely increase the qualify of our code and i think its up for discussion.

here are the some of the rules that i had

```
  "rules": {
    "prefer-const": "error",
    "no-var": "error",
    "semi": ["warn", "always"],
    "quotes": ["off", "single"],
    "indent": ["error", 2],
    "react/prop-types": [0],
    "comma-dangle": ["error", "always-multiline"]
  }
```

**Comment by johnpyp** [comment]
Ok, I'll try the airbnb config, and I'm willing to resolve the merge conflicts.

**Comment by johnpyp** [comment]
I have PR basically ready, however it will cause *tons* of merge conflicts with the active PRs. I'd like to get to a point where we don't have any active PRs being worked on so people can start from the linted branch properly.
