### ISSUE TITLE
Mobile Responsive Application

### ISSUE THREAD

**Issue by sayansaha1143** [codeforboston/communityconnect#38]
We need to make sure the application looks and works similar to the normal application in a phone view. Fixing minor issues like being able to click the "Category" drop-down while viewing on a phone, could be a start.

**Comment by galiat** [comment]
issues:
- [ ] Org card on mobile too small
- [ ] Clicking Category dropdown not working

**Comment by galiat** [comment]
![](http://g.recordit.co/dh8eHT8MEm.gif)
