### ISSUE TITLE
Feature Request: Add icon next to name of resource to help users identify category

### ISSUE THREAD

**Issue by mzxbliss** [codeforboston/communityconnect#39]
For each resource listing, we can add an icon right next to the name of the organization so it's easy to see what type of resource it is. For example, if it's a park, the icon chosen can be a tree and if it's a farm, it can be represented it with a carrot or corn.

The goal is to easily differentiate this resource from other categories once we implement the free-text search input

Free icons/assets can be found here: https://fontawesome.com/

**Comment by Khoawala** [comment]
What if an organization is in multiple categories? Like North Shore Workforce Investment Board Center.

**Comment by mzxbliss** [comment]
I didn't think about that. I thought it was a 1:1 relationship! We may just want to kill this ticket since I heard there could be more categories added in the future and those will be missing icons if no one maintain it
