### ISSUE TITLE
User Login Form

### ISSUE THREAD

**Issue by ndesai06** [codeforboston/communityconnect#46]
Login Form - username and password with forgot password/username option (see below - without the facebook, twitter, google, linkedin account option)

![basic-html5-login-form-with-massive-look](https://user-images.githubusercontent.com/42190870/46051098-88dd4580-c105-11e8-957a-8a06d20fc8e5.jpg)

Login information will allow users to "favorite" certain resources to make them more accessible. This can be implemented by having a tab at the top of the web app. Currently, the category list is located on the top right of the web page. If we move the category list next to the resources themselves (similar to Finda - see below), this will free up the room at the top bar and to include user specific information.

<img width="1071" alt="screen shot 2018-09-25 at 8 55 02 pm" src="https://user-images.githubusercontent.com/42190870/46051048-5a5f6a80-c105-11e8-97b2-5b626d97d621.png">

**Comment by Khoawala** [comment]
We are going with deep linking for favorites
