### ISSUE TITLE
Add comments to code

### ISSUE THREAD

**Issue by sayansaha1143** [codeforboston/communityconnect#66]
We need to add comments to our code for all the new people who come in and start working on it. It would be really helpful as the code is growing with every PR. We can do this along with code refactoring.

We can start by adding comments to our important files like app.js and header.js.

**Comment by alxhghs** [comment]
I agree that this is important. As I'm learning the codebase, it could be a good practice for me to go through and add comments as I'm learning what everything does. I'd be happy to work on this.
