### ISSUE TITLE
Issue with Multiple Resources on 1 Address

### ISSUE THREAD

**Issue by ndesai06** [codeforboston/communityconnect#67]
When multiple health resources have the same address, no information is shown when clicked on the cluster (goes from a blue cluster to yellow) at that point. It would be great to see a tiled list of all the resources available at the address in a similar fashion to the list on the left side of the screen.

Ex. 300 Ocean Avenue, Revere, MA 02151 has 10 health resources: 
   1. MILC (Mother Infant Lactation Club) Breastfeeding Support Group
   2. Reach Out and Read
   3. WIC (Women, Infants, Children)
   4. Cambodian Diabetic Coaching Program
   5. CORE Health
   6. Diabetes Eye Program
   7. Revere on the Move
   8. ARCH (Access to Resources for Community Health
   9. Revere HealthCare Center
   10. Department of Transitional Assistance (DTA)

**Comment by microcat49** [comment]
Hey @ndesai06, could I work on this one?

**Comment by ndesai06** [comment]
Hey @microcat49! Yeah you can definitely work on it!
