### ISSUE TITLE
On the Org Card, Facebook URL does not work

### ISSUE THREAD

**Issue by galiat** [codeforboston/communityconnect#83]
Example:

![image](https://user-images.githubusercontent.com/757518/47446532-6fbdc800-d789-11e8-8ea4-9a1b29007c8f.png)

**Comment by Atul9** [comment]
@galiat I would like to work on this

**Comment by galiat** [comment]
Woah thank you, @Atul9 ! Are you involved with Code for Boston? Its fine if you are not- was just wondering because I don't see you in our slack.
