### ISSUE TITLE
Add logo to header.js

### ISSUE THREAD

**Issue by mzxbliss** [codeforboston/communityconnect#99]
![cc-mini-logo](https://user-images.githubusercontent.com/18015919/48105094-1da68900-e204-11e8-9b98-89ece0443fa0.png)
![cc-large-logo](https://user-images.githubusercontent.com/18015919/48105095-1ed7b600-e204-11e8-8cc0-3b5e2df81ab8.png)

**Comment by tshin7** [comment]
Should this issue be closed?

**Comment by ndesai06** [comment]
#115
